# Generated by Django 4.2.6 on 2023-10-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post_like',
            name='session_id',
            field=models.CharField(max_length=32),
        ),
    ]
