# Generated by Django 4.2.6 on 2023-10-11 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_comment_posts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
