# Generated by Django 4.2.6 on 2023-10-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_post_like_session_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment_Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.IntegerField()),
                ('comment_id', models.IntegerField()),
                ('session_id', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='dislikes',
            new_name='num_dislikes',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='num_likes',
        ),
    ]
