# Generated by Django 4.2.6 on 2023-10-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comment_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
