# Generated by Django 4.2.6 on 2023-10-15 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_comment_dislikes_comment_likes_comment_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='time',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='date',
        ),
    ]
